name: Language Stats

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Run language stats script
        run: |
          python stats.py
          cat language_stats.json

      - name: Upload JSON result as artifact
        uses: actions/upload-artifact@v4
        with:
          name: language-stats
          path: language_stats.json

